name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Verify Playwright browsers cache
        run: ls -la /home/runner/.cache/ms-playwright
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: playwright-report/
          retention-days: 7
